### ISSUE TITLE
(新功能)已读标识

### ISSUE THREAD

**Issue by hu3rror** [gaodeng/Biu-for-ReadHub#4]
希望能添加一下已读标识，具体情况可参考Unread中的两个模式：
1. 点击后自动变灰
2. 屏幕划过的新闻自动变灰(用于只看标题，不点进去，依然能标记已读)

现在UX已经很好了，特别是新版本的下拉刷新，默默祝可以上架。

**Comment by nickqiao** [comment]
请问 Unread的两个模式指什么？哪里参考？

**Comment by hu3rror** [comment]
先祝新年快乐～

抱歉没有明确说明，Unread是iOS的一款RSS阅读器。

具体功能名称如图1中的标记，分别是点击自动标记已读、滚动自动标记已读
具体实现如动图所示。

图1：
![图1](https://i.loli.net/2018/02/16/5a85b7c773dea.png)

动图1：

![screenrecording_02-16-2018-00-33-25](https://user-images.githubusercontent.com/19755727/36268989-fcc41b56-12b2-11e8-9f7d-7ba9b2b88663.gif)


另一个滚动自动标记因为太大了，所以只能存云盘，希望不嫌麻烦点击一下。
[动图2](https://www.jianguoyun.com/p/DUZm2cgQ7-reBhix00M)
